import Head from 'next/head'

export default function hours() {
  return (
    <div>
      <Head>
        <title>MAGAL Hours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="left">
        <h2>Working Hours</h2>
      </div>

      <h3>Monday-Thursday: 5pm-11pm</h3>
      <h3>Friday: 5pm-12am</h3>
      <h3>Saturday: 3pm-12am</h3>
      <h3>Sunday: 3pm-10pm</h3>
      
      <div class="tele">
        <p>Telephone: (213)383-1909</p>
      </div>
    </div>
  )
}
