import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>MAGAL Korean BBQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="left">
        <h2>Reservation Now Available Online</h2>
      </div>

      <h3>About our Business</h3>
      <p>
        Originally from South Korea, we offer high quality, Korean-style meats where you will have the chance 
        to grill the meat to your taste. We have over 15 different types of meat that you could choose from,
        all of them of the highest quality. We also offer a plethora of traditional Korean dishes, not to mention
        our collection of famous side dishes. Some of our most popular dishes include Beef Skirt, Beef Brisket,
        Short Rib Sushi, Pork Skirt, Pork Belly, and much more.
      </p>

      <h3>What We Offer</h3>
      <p>
        A night out for Korean BBQ typically tends to be a whole production involving long wait times or all-you-can-eat deals you didn't ask for. 
        But Magal is the opposite. This small, bright, loud spot takes last-minute reservations and the quality of meat and banchan is excellent. And even if you don’t normally like EDM, you’ll find that slowly but surely stuffing your face with bulgogi and soju to the beat of 
        house music is a religious experience not unlike blasting Alanis Morisette while driving down Sunset alone at night.
      </p>

      <div className="tele">
        <p>Telephone: (213)383-1909</p>
      </div>
    </div>
  )
}
