import Head from 'next/head'
import Image from 'next/image'

export default function menu() {
  return (
    <div>
      <Head>
        <title>MAGAL Menu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="menu">
        <Image src='/menu.jpg' width={1000} height={1400} />
      </div>
    </div>
  )
}